Switch to a trust based CI config.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,37 +1,70 @@
-sudo: false
+# Based on the "trust" template v0.1.1
+# # https://github.com/japaric/trust/tree/v0.1.1
+
+dist: trusty
 language: rust
-cache: cargo
-rust:
-  - stable
-  - beta
-  - nightly
+services: docker
+sudo: required
 
-before_script:
-  - |
-    pip install 'travis-cargo<0.2' --user &&
-    (cargo install rustfmt || true) &&
-    export PATH=$HOME/.local/bin:$PATH &&
-    export PATH=$HOME/.cargo/bin:$PATH
-
-script:
-  - |
-    cargo fmt -- --write-mode=diff &&
-    travis-cargo build &&
-    travis-cargo test
-
-addons:
-  apt:
-    packages:
-      - libcurl4-openssl-dev
-      - libelf-dev
-      - libdw-dev
-
-after_success:
-  - travis-cargo --only stable coveralls --no-sudo --exclude-pattern="src/main.rs,src/new.rs,target/debug/build/"
+rust: stable
 
 env:
   global:
-  - TRAVIS_CARGO_NIGHTLY_FEATURE="clippy"
+    - CRATE_NAME=cobalt
+    # default job
+    - TARGET=x86_64-unknown-linux-gnu
+
+matrix:
+  include:
+    # Linux
+    # - env: TARGET=x86_64-unknown-linux-gnu  # this is the default job
+    - env: TARGET=x86_64-unknown-linux-musl
+
+    # OSX
+    - env: TARGET=x86_64-apple-darwin
+      os: osx
+
+    # Testing other channels
+    - env: TARGET=x86_64-unknown-linux-gnu
+      rust: beta
+    - env: TARGET=x86_64-unknown-linux-gnu
+      rust: nightly
+
+install:
+  - sh ci/install.sh
+  - source ~/.cargo/env || true
+
+script:
+  - bash ci/script.sh
+
+before_deploy:
+  - sh ci/before_deploy.sh
+
+cache: cargo
+before_cache:
+    # Travis can't cache files that are not readable by "others"
+    - chmod -R a+r $HOME/.cargo
+
+branches:
+  only:
+    # release tags
+    - /^v\d+\.\d+\.\d+.*$/
+    - master
+
+# TODO: Upload coverage
+#after_success:
+ #- travis-cargo --only stable coveralls --no-sudo --exclude-pattern="src/main.rs,src/new.rs,target/debug/build/"
+
+#deploy:
+  #api_key:
+    #secure: IzxVmMO+mVWc4BSoB7Ek7L6Ye5FNrCI4fb/pIFitrQRmP3Cpuw7qMm5sxL5niiGaMRJHwce07ukyKsCNgs+64k8VwToUDPWy4F7+EbIHrjDOJtIY8TME+hUeaCmkMysuqUj1oKtDS+l8F+Yc42ZXNMqz/1kF/h6sGTRSmlzR3mc=
+  #file_glob: true
+  #file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
+  #on:
+    #condition: $TRAVIS_RUST_VERSION = stable
+    #tags: true
+  #provider: releases
+  #skip_cleanup: true
 
 notifications:
   webhooks:
